### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### Add Bicycle Type
POST http://localhost:8080/api/v1/bicycleType
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "brand": "TechnoBike",
  "model": "CX600D4",
  "productionYear": 2018
}

### Get Bicycle Types
GET http://localhost:8080/api/v1/bicycleType
Accept: application/json
Content-Type: application/json

### Get Bicycle Type by ID
GET http://localhost:8080/api/v1/bicycleType/2
Accept: application/json
Content-Type: application/json

### Update Bicycle Type
PUT http://localhost:8080/api/v1/bicycleType
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "brand": "Tesla",
  "model": "Model B",
  "productionYear": 2077
}

### Delete Bicycle Type
DELETE http://localhost:8080/api/v1/bicycleType/2
Accept: application/json
Content-Type: application/json