### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### Add Rent
POST http://localhost:8080/api/v1/rent
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "userId": 2,
  "bicycleId": 2
}

### Get Rents
GET http://localhost:8080/api/v1/rent
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### Get Rent by ID
GET http://localhost:8080/api/v1/rent/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### Update Rent
PUT http://localhost:8080/api/v1/rent
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": 1,
  "userId": 1,
  "bicycleId": 3
}

### Delete Rent
DELETE http://localhost:8080/api/v1/rent/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}