### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### get all rental reports
GET http://localhost:8080/api/v1/reports/rentals
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all rental reports with user id
GET http://localhost:8080/api/v1/reports/rentals/user/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all rental reports with bicycle number
GET http://localhost:8080/api/v1/reports/rentals/bicycle/bike1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get rental report with rentalNumber
GET http://localhost:8080/api/v1/reports/rentals/OJYRP8582834505
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all rental payment reports
GET http://localhost:8080/api/v1/reports/rentals/payments
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all rental payment reports with user id
GET http://localhost:8080/api/v1/reports/rentals/payments/user/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get rental payment report with rentalNumber
GET http://localhost:8080/api/v1/reports/rentals/payments/OJYRP8582834505
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}